export const GETPOSTSREQUEST = "GET_POSTS_REQUEST"
export const GETPOSTSUCCESS = "GET_POST_SUCCESS"
export const GETPOSTSFAILURE = "GET_POST_FAILURE"

export const CREATEPOSTSREQUEST = "CREATE_POSTS_REQUEST"
export const CREATEPOSTSUCCESS = "CREATE_POST_SUCCESS"
export const CREATEPOSTSFAILURE = "CREATE_POST_FAILURE"

export const UPDATEPOSTREQUEST = "UPDATE_POST_REQUEST"
export const UPDATEPOSTSUCCESS = "UPDATE_POST_SUCCESS"
export const UPDATEPOSTFAILURE = "UPDATE_POST_FAILURE"

export const DELETEPOSTREQUEST = "DELETE_POST_REQUEST"
export const DELETEPOSTSUCCESS = "DELETE_POST_SUCCESS"
export const DELETEPOSTFAILURE = "DELETE_POST_FAILURE"

export const CREATEUSERREQUEST = "CREATE_USER_REQUEST"
export const CREATEUSERSUCCESS = "CREATE_USER_SUCCESS"
export const CREATEUSERFAILURE = "CREATE_USER_FAILURE"

export const FINDUSERREQUEST = "FIND_USER_REQUEST"
export const FINDUSERSUCCESS = "FIND_USER_SUCCESS"
export const FINDUSERFAILURE = "FIND_USER_FAILURE"

export const SHOWCREATEPOSTMODAL = "SHOW_CREATE_POST_MODAL"
export const HIDECREATEPOSTMODAL = "HIDE_CREATE_POST_MODAL"